var mongoose = require('mongoose');
var OrganizationSchema = new mongoose.Schema({
    organizationId : Number,
    hasEmployee : Number,
    orgLevel : Number,
    orgOrder : Number,
    enterpriseTypeId : String,
    code : String,
    name : String,
    oldName : String,
    englishName : String,
    abbreviation : String,
    establishDecideNum : String,
    decisionLevel : String,
    orgTypeId : Number,
    effectiveStartDate : Number,
    effectiveEndDate : String,
    establishedDate : String,
    orgManagerId : String,
    orgParentId : Number,
    directManager : String,
    address : String,
    nationId : Number,
    provinceId : String,
    businessCode : String,
    taxCode : String,
    bankAccount : String,
    bankId : String,
    bankAgency : String,
    phoneNumber : String,
    establishmentReason : String,
    description : String,
    createdTime : Number,
    modifiedTime : Number,
    expiryDecideNum : String,
    expiryDescription : String,
    isActive : Number,
    isLocked : Number,
    status : Number,
    path : String,
    createdBy : Number,
    modifiedBy : Number,
    positionBoundaryNumber : String,
    expiryRelationTypeId : String,
    rewardOrganizationId : String,
    fullPath : String,
    orgCodePath : String,
    orgLevelManage : Number,
    isInsuranceOrg : String,
    generateOrgOrder : String,
    startWorkingDate : String,
    endWorkingDate : String,
    criterialId : String,
    criterialName : String,
    q1Numbera : String,
    totalEmp : Number,
    vtpLastUpdate: Date,
    forumCategoryCode : Number,
    forumParentCategoryCode : Number,
});

mongoose.model('Organization', OrganizationSchema);

module.exports = mongoose.model('Organization');
